[phases.install]
cmds = [
  "npm install -g pnpm@11.1.2",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm turbo build --filter=@chess/server"]

[start]
cmd = "node apps/server/dist/index.js"
